image: ansible/ansible:default
#image: base/archlinux

stages:
  - check
#  - test
#  - deploy

before_script:
  - ./extensions/setup/setup.sh
  - echo $ANSIBLE_VAULT_PASSWORD > .vpass
  - sha256sum .vpass

check:
  stage: check
  script:
    - cd plays
    # ANSIBLE0010: Package installs should not use latest
    # ANSIBLE0016: Tasks that run when changed should likely be handlers
    # ANSIBLE0002: Trailing whitespace
    - ansible-lint *.yml -x ANSIBLE0010,ANSIBLE0016,ANSIBLE0002
    - ansible-playbook *.yml --vault-password-file ../.vpass --syntax-check -i ../testing.ini

#test:
#  stage: test
#  script:
#    # Deploy the role in test environment.
#    - sudo ./plays/testing-play-examplePlay.sh

#deploy:
#  stage: deploy
#  script:
#    # TODO: Create environment in GitLab for deployment, only master branch
#    - ./plays/testing-play-examplePlay.sh
