- name: Prerequirements for Ansible
  hosts: examplePlay
  gather_facts: false
  become: true
  roles:
    - role: ansible-prerequirements
      tags: prerequirements
- name: All roles
  hosts: examplePlay
  become: true
  roles:
    - role: common
      tags: common
#   - role: additionalRole
#     tags: additionalRole
